version: '3'

services:
  django_gunicorn:
      volumes:
        - static:/static
      env_file:
        - .env
      build:
        context: .
      ports:
        - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  api:
    image: api
    container_name: api
    build:
      context: .
    depends_on:
      - db
    environment:
      POSTGRES_DB: djangoapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command: python manage.py runserver 0.0.0.0:5001
    ports:
      - 5001:5001
    restart: on-failure
  
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nurpolat
      - POSTGRES_PASSWORD=nurpolat
      - POSTGRES_DB=blog_db


volumes:
  postgres_data:
  static:

networks:
  nginx_network:
    name: nginx_network